<x-layout>
    <table>
        <tr>
            <th>id</th>
            <th>Логин</th>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Почта</th>
        </tr>
        @foreach($arr as $account)
            <tr>
                <td>{{$account['id']}}</td>
                <td>{{$account['login']}}</td>
                <td>{{$account['profile']['name']}}</td>
                <td>{{$account['profile']['surname']}}</td>
                <td>{{$account['profile']['email']}}</td>
            </tr>
        @endforeach
    </table>
</x-layout>
